<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bravo.proto

namespace App\Service\GrpcClient\Bravo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>bravo.SettingsReply</code>
 */
class SettingsReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string field1 = 1;</code>
     */
    protected $field1 = '';
    /**
     * Generated from protobuf field <code>bool field2 = 2;</code>
     */
    protected $field2 = false;
    /**
     * Generated from protobuf field <code>int32 field3 = 3;</code>
     */
    protected $field3 = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field1
     *     @type bool $field2
     *     @type int $field3
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Bravo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string field1 = 1;</code>
     * @return string
     */
    public function getField1()
    {
        return $this->field1;
    }

    /**
     * Generated from protobuf field <code>string field1 = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setField1($var)
    {
        GPBUtil::checkString($var, True);
        $this->field1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool field2 = 2;</code>
     * @return bool
     */
    public function getField2()
    {
        return $this->field2;
    }

    /**
     * Generated from protobuf field <code>bool field2 = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setField2($var)
    {
        GPBUtil::checkBool($var);
        $this->field2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 field3 = 3;</code>
     * @return int
     */
    public function getField3()
    {
        return $this->field3;
    }

    /**
     * Generated from protobuf field <code>int32 field3 = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setField3($var)
    {
        GPBUtil::checkInt32($var);
        $this->field3 = $var;

        return $this;
    }

}

